" $Id$
" Travis Meisenheimer <tmeisenheimer@users.sourceforge.net>
" My personal .vimrc file that adds basic functionality
" and makes vim easier to use.
" Make sure to set $VIM to the location of your system's vim 
" syntax and global vimrc files.  Set this in /etc/profile or
" or your shell's .rc file.
" Last updated Sept 25, 2004

syntax on
set noautoindent
set smartindent
set nonumber
filetype plugin on
filetype indent off
set history=1000
set nocompatible
set showmatch
set hlsearch
set incsearch
"set ignorecase
set showmode
set tabstop=8
set expandtab
set shiftwidth=8
set backspace=2
set nowrap
set ruler
set magic
set dictionary=/usr/share/dict/words
"set t_kb=
"fixdel
