# $Id$
#
# Z shell configuration file
#
# Author: Travis Meisenheimer <travis@indexoutofbounds.com>
#
# Works on zsh versions > 4.0.9.
#********************************************************************

# Source /etc/profile
if [ -f /etc/profile ]; then
    source /etc/profile
fi

# Some environment variables and settings I like
path=($path $HOME/bin)
[[ -d $HOME/bin-`uname | tr "[:upper:]" "[:lower:]"` ]] && path=($path $HOME/bin-`uname | tr "[:upper:]" "[:lower:]"`)
export USER=`id -un`
export LANG="en_US"
export HOSTNAME=`/bin/hostname`
export LC_ALL=POSIX
export EDITOR='vim'
export PAGER='less'
export ZLS_COLORS=$LS_COLORS
export ZSHDIR=$HOME/.zsh
export ZSHCONF=$HOME/.zshrc
export SSHSOURCE=`echo $SSH_CONNECTION | awk '{print $1}'`
export SVN_URL=svn+ssh://tmeisenh@dev.indexoutofbounds.com/home/tmeisenh/svn
export GIT_URL=tmeisenh@dev.indexoutofbounds.com/home/tmeisenh/git
bindkey -v        #vi key bindings

# Set term if not set
#if [ "$TERM" = "" -o "$TERM" = "unknown" ]; then
#    $TERM="vt100"
#    if [ "`uname`" = "Linux" ]; then
#        $TERM="linux"
#    fi
#fi
     
# Set Logs and History
watch=(notme root)

# Create $user history files
HISTSIZE=10000
HISTFILE=$HOME/.zsh_history
SAVEHIST=65536
DIRSTACKSIZE=16

# Load some cool zsh features
typeset -U path cdpath manpath fpath
autoload -U compinit && compinit
autoload -U zed
autoload zmv
autoload zcalc
autoload zargs
autoload colors; colors
autoload history-search-end
autoload zkbd
zmodload -i zsh/complist
autoload -U predict-on && \
zle -N predict-on             && \
zle -N predict-off            && \
bindkey "^X^Z" predict-on     && \
bindkey "^Z" predict-off      && \

# Set root paths
# For root users, ensure that /usr/local/sbin, /usr/sbin, and /sbin
# are in the path.
if [ "`id -u`" = "0" ]; then
    echo $PATH | grep /usr/local/sbin 1> /dev/null 2> /dev/null
    if [ ! $? = 0 ]; then
        PATH=/usr/local/sbin:/usr/sbin:/sbin:$PATH
    fi
fi

# Set display colors - This is a GNU coreutils ability only.  We use 
# /etc/DIR_COLORS or our own, modified version which we store in ~.
gdircolors &>/dev/null 2>&1 && alias dircolors="gdircolors" 
[[ -f ~/.dir_colors ]] && eval `dircolors -b ~/.dir_colors` 

# System wide aliases
source $ZSHCONF/aliases.zsh

# Completion Options
source $ZSHCONF/options.zsh

source $ZSHCONF/prompt.zsh

source $ZSHCONF/keys.zsh

# Shell functions

# Use hard limits, except for a smaller stack and no core dumps
unlimit
limit stack 8192
limit core 0
limit coredumpsize 0
limit -s

source $ZSHCONF/shellfunctions.zsh

# set command completions
source $ZSHCONF/completions.zsh

# Set envrionment stuff
source $ZSHCONF/environment.zsh

# Umask settings 
# -rw-r--r--
 umask 022

# -rw-rw-r--
# umask 2

# -rw-------
#umask 007

# If root set unmask to 077 to allow new files to remain private 
if [ "`id -u`" = "0" ];    then
    umask 077
fi

# End
